import type { Club, Service } from './types';

export const mockServices: Service[] = [
  { id: 's1', name: 'Standard Court Booking', price: 20, durationMinutes: 60, description: '1 hour court rental.' },
  { id: 's2', name: 'Premium Court Booking', price: 30, durationMinutes: 60, description: '1 hour premium court rental with better surface.' },
  { id: 's3', name: 'Coaching Session', price: 50, durationMinutes: 60, description: '1 hour session with a professional coach.' },
  { id: 's4', name: 'Evening Slot Surcharge', price: 25, durationMinutes: 60, description: '1 hour court rental during peak evening hours.' },
];

export const mockClubs: Club[] = [
  {
    id: 'club1',
    name: 'Grand Slam Tennis Club',
    sport: 'Tennis',
    location: 'Downtown, Sportsville',
    description: 'Premier tennis facility with 10 clay courts and 5 hard courts. Professional coaching available. Open 7 days a week.',
    images: ['https://placehold.co/600x400.png?text=Tennis+Court+1', 'https://placehold.co/600x400.png?text=Tennis+Court+2'],
    services: [mockServices[0], mockServices[2]],
    contactEmail: 'info@grandslamtennis.com',
    contactPhone: '555-0101',
    rating: 4.8,
    amenities: ['Parking', 'Showers', 'Pro Shop', 'Cafe'],
  },
  {
    id: 'club2',
    name: 'Shuttle Masters Badminton Center',
    sport: 'Badminton',
    location: 'North Suburb, Sportsville',
    description: 'State-of-the-art badminton center with 8 professional courts. Equipment rental and group classes offered.',
    images: ['https://placehold.co/600x400.png?text=Badminton+Court+1', 'https://placehold.co/600x400.png?text=Badminton+Hall'],
    services: [mockServices[0], mockServices[1]],
    contactEmail: 'contact@shuttlemasters.com',
    rating: 4.5,
    amenities: ['Parking', 'Changing Rooms', 'Water Fountain'],
  },
  {
    id: 'club3',
    name: 'The Squash Box',
    sport: 'Squash',
    location: 'West End, Sportsville',
    description: 'Friendly and competitive squash club with 6 well-maintained courts. Regular tournaments and leagues.',
    images: ['https://placehold.co/600x400.png?text=Squash+Court+View', 'https://placehold.co/600x400.png?text=Squash+Players'],
    services: [mockServices[0], mockServices[3]],
    contactPhone: '555-0103',
    rating: 4.2,
    amenities: ['Lockers', 'Viewing Gallery'],
  },
  {
    id: 'club4',
    name: 'Padel Palace',
    sport: 'Padel',
    location: 'Eastside Park, Sportsville',
    description: 'Modern Padel club with 4 panoramic outdoor courts and 2 indoor courts. Social events and coaching for all levels.',
    images: ['https://placehold.co/600x400.png?text=Padel+Court+Night', 'https://placehold.co/600x400.png?text=Padel+Action'],
    services: [mockServices[1], mockServices[2]],
    contactEmail: 'play@padelpalace.com',
    rating: 4.9,
    amenities: ['Parking', 'Cafe', 'Equipment Rental', 'Floodlights'],
  },
];
